#!/usr/bin/env bash
set -e
set -x

/docker/run_all.sh /docker/pre_init

/usr/bin/supervisord -c /etc/supervisor/supervisord.conf
#/usr/bin/supervisorctl

/docker/run_all.sh /docker/post_init

while ( true )
do
  echo "Detach with Ctrl-p Ctrl-q. Dropping to shell"
  sleep 1
  /bin/bash
done
